version: "3.8"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: cjw-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app:rw
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cjw_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cjw-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: cjw-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cjw_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/app/db/init_extra.sql:/docker-entrypoint-initdb.d/init_extra.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
